# Generated by Django 4.2 on 2023-04-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_total_price_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
