# Generated by Django 4.2 on 2023-04-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_pizza_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
