# Generated by Django 4.2 on 2023-04-17 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_pizza_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.pizza'),
        ),
    ]
